---
title: "on the origin of citations"
author: "Iuri"
date: "September 15, 2015"
output:
  word_document: default
  html_document:
    fig_caption: yes
    fig_height: 6
    fig_width: 10
    highlight: espresso
    number_sections: yes
    self_contained: no
    theme: cerulean
    toc: yes
---
# Load the data  

```{r}
counts_raw=read.delim("data/counts-raw.txt.gz")
counts_norm=read.delim("data/counts-norm.txt.gz")
```

# Data exploration

What is the distribution of authors in all the articles in the data?

```{r author_histogram, fig.cap="Figue 1: Number of authors per article"}
hist(counts_raw$authorsCount, main="Authors per paper", xlab="# authors")

```

Papers on Facebook!
```{r, facebook_hist, xlim = c(0,10), fig.cap="Figure 2: Number of Facebook shares per article", echo=FALSE}
hist(counts_raw$facebookShareCount, main="Facebbok shares", xlab="number of shares")

```
The average number of Facebook shares per paper is `r mean(counts_raw$facebookShareCount)`


# dplyr

```{r}
library(dplyr)

```



```{r}
research=filter(counts_raw,articleType=="Research Article")
research_2006=filter(research, year==2006)
nrow(research_2006)
research_2006_fb=filter(research, year==2006, facebookCommentCount > 0 , grepl("Infectious Diseases",plosSubjectTags))
nrow(research_2006_fb)
```
```{r}
colnames(research)
article_info=select(research, doi, pubDate, journal, title, articleType, authorsCount)
colnames(article_info)
article_info


metrics=select(research, contains("Count"), -authorsCount, f1000Factor)
colnames(metrics)


head(select(research, journal))
slice(article_info,1:3)


y=filter(counts_raw, articleType== "Research Article", year <= 2008, mendeleyReadersCount > 15, wosCountThru2011 < 10  )
y

head(y)
nrow(y)

research=filter(counts_raw,articleType=="Research Article")
facebook_2006=research %>% filter(year ==2006) %>% select(contains("facebook"))
head(facebook_2006)



arrange 

research %>% arrange(authorsCount, wosCountThru2011) %>% 
  select(authorsCount, wosCountThru2011) %>%
  slice(1:10)

challenge 1
research %>% arrange(desc(wosCountThru2011)) %>% 
  select(title) %>%
  slice(1:3)

chalenge 2
research %>% arrange(desc(authorsCount)) %>% 
  select (authorsCount, title, journal, plosSubjectTags) %>%
  slice (1:3)



research=research %>% mutate(weeksSincePublished = daysSincePublished / 7 , yearsSincePublished = weeksSincePublished/52)
research %>% select(contains("Since")) %>% slice(1:10)
research %>% summarize(plos_mean=mean(plosCommentCount),num=n())

group_by  

research %>% group_by(journal,year) %>% 
  summarize(tweets_mean = mean(backtweetsCount)) 

research %>% group_by(journal) %>% 
  summariz

Challenge 3

tweets= research %>% group_by(journal) %>%
  summarize(num = n(), 
            sem = sd(backtweetsCount) / sqrt(num))
tweets




```

arrange function


